//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Converter_Smeta_BusGov {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Converter_Smeta_BusGov.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited with XMLSpy v2007 (http://www.altova.com) by Alexander (Lanit) --&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://bus.gov.ru/types/2&quot;
        ///           xmlns:t=&quot;http://bus.gov.ru/types/1&quot; targetNamespace=&quot;http://bus.gov.ru/types/2&quot;
        ///           elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///    &lt;xs:import namespace=&quot;http://bus.gov.ru/types/1&quot; schemaLocation=&quot;Types.xsd&quot;/&gt;
        ///    &lt;xs:complexType name=&quot;annualBalanceF0503762Type&quot;&gt;
        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string balance {
            get {
                return ResourceManager.GetString("balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited with XMLSpy v2007 (http://www.altova.com) by Alexander (Lanit) --&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://bus.gov.ru/external/1&quot; xmlns:t=&quot;http://bus.gov.ru/types/1&quot; xmlns:b=&quot;http://bus.gov.ru/types/2&quot; xmlns:f=&quot;http://bus.gov.ru/types/3&quot; targetNamespace=&quot;http://bus.gov.ru/external/1&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://bus.gov.ru/types/1&quot; schemaLocation=&quot;Types.xsd&quot;/&gt;
        ///	 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string External {
            get {
                return ResourceManager.GetString("External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited with XMLSpy v2007 (http://www.altova.com) by Alexander (Lanit) --&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://bus.gov.ru/types/3&quot;
        ///           xmlns:t=&quot;http://bus.gov.ru/types/1&quot; targetNamespace=&quot;http://bus.gov.ru/types/3&quot;
        ///           elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///    &lt;xs:import namespace=&quot;http://bus.gov.ru/types/1&quot; schemaLocation=&quot;Types.xsd&quot;/&gt;
        ///    &lt;xs:complexType name=&quot;financialActivityPlan2020Typ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string financialActivityPlan {
            get {
                return ResourceManager.GetString("financialActivityPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited with XMLSpy v2007 (http://www.altova.com) by Alexander (Lanit) --&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://bus.gov.ru/fk/1&quot; xmlns:t=&quot;http://bus.gov.ru/types/1&quot; targetNamespace=&quot;http://bus.gov.ru/fk/1&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://bus.gov.ru/types/1&quot; schemaLocation=&quot;Types.xsd&quot;/&gt;
        ///	&lt;xs:element name=&quot;confirmation&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Протокол заг [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string FK {
            get {
                return ResourceManager.GetString("FK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited with XMLSpy v2007 (http://www.altova.com) by Alexander (Lanit) --&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:t=&quot;http://bus.gov.ru/types/1&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://bus.gov.ru/NSI/1&quot; targetNamespace=&quot;http://bus.gov.ru/NSI/1&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:import namespace=&quot;http://bus.gov.ru/types/1&quot; schemaLocation=&quot;Types.xsd&quot;/&gt;
        ///	&lt;xs:element name=&quot;consRegSta [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string NSI {
            get {
                return ResourceManager.GetString("NSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!-- edited with XMLSpy v2007 (http://www.altova.com) by Alexander (Lanit) --&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://bus.gov.ru/types/1&quot; targetNamespace=&quot;http://bus.gov.ru/types/1&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot;&gt;
        ///	&lt;xs:complexType name=&quot;actionGrantType&quot;&gt;
        ///		&lt;xs:annotation&gt;
        ///			&lt;xs:documentation&gt;Операции с целевыми средствами из бюджета&lt;/xs:documentation&gt;
        ///		&lt;/xs:annotation&gt;
        ///		&lt;xs:complexContent&gt;
        ///			&lt;xs:exten [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
    }
}
